server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  profiles:
#    active: dev
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka